import {StyleSheet} from 'react-native';

export const PURPLE = '#5A31C2';
export const BLUE = '#05A9F4';
export const BORDER = '#DFE1E7';
export const TEXT = '#202124';
export const MUTED = '#6F737B';

export const circularStyles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: PURPLE,
  },
  headerSafe: {
    backgroundColor: PURPLE,
  },
  header: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    backgroundColor: PURPLE,
  },
  headerButton: {
    width: 34,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 6,
  },
  statusShortcut: {
    width: 31,
    height: 31,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  page: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  tabs: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 28,
    paddingTop: 25,
    paddingBottom: 14,
  },
  tabButton: {
    height: 39,
    flex: 1,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  activeTab: {
    backgroundColor: BLUE,
    borderColor: BLUE,
  },
  tabText: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  createContent: {
    paddingHorizontal: 28,
    paddingTop: 17,
    paddingBottom: 44,
  },
  field: {
    minHeight: 45,
    borderWidth: 1,
    borderColor: '#D8D8D8',
    borderRadius: 7,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 15,
    marginBottom: 17,
    color: TEXT,
    fontSize: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateField: {
    backgroundColor: '#F4F4F4',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingVertical: 7,
  },
  dateLabel: {
    color: '#6F737B',
    fontSize: 11,
    lineHeight: 14,
  },
  dateValue: {
    color: TEXT,
    fontSize: 14,
    lineHeight: 19,
  },
  fieldText: {
    color: TEXT,
    fontSize: 14,
  },
  required: {
    color: '#FF0909',
  },
  uploadField: {
    height: 77,
    borderWidth: 1,
    borderColor: '#D8D8D8',
    borderRadius: 7,
    backgroundColor: '#FFFFFF',
    paddingLeft: 15,
    paddingRight: 24,
    marginBottom: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  uploadText: {
    color: TEXT,
    fontSize: 14,
  },
  uploadButton: {
    width: 61,
    height: 60,
    borderWidth: 1,
    borderColor: '#FF0712',
    borderStyle: 'dashed',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButton: {
    height: 45,
    borderRadius: 6,
    backgroundColor: PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  listContent: {
    paddingHorizontal: 20,
    paddingTop: 17,
    paddingBottom: 34,
  },
  circularCard: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 7,
    backgroundColor: '#FFFFFF',
    marginBottom: 16,
    overflow: 'hidden',
  },
  cardTitleBar: {
    height: 34,
    backgroundColor: '#F3F3F3',
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  cardTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  cardBody: {
    paddingHorizontal: 15,
    paddingTop: 18,
    paddingBottom: 16,
  },
  metaRow: {
    flexDirection: 'row',
    marginBottom: 22,
  },
  metaColumn: {
    flex: 1,
  },
  metaLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 5,
  },
  metaLabel: {
    color: MUTED,
    fontSize: 12,
  },
  metaValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
    paddingLeft: 16,
  },
  attachmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  attachmentIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#F2F2F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  attachmentText: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  detailContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 36,
  },
  detailCard: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 7,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  detailBody: {
    paddingHorizontal: 15,
    paddingTop: 16,
    paddingBottom: 18,
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  detailCell: {
    width: '50%',
    marginBottom: 20,
  },
  detailLabel: {
    color: MUTED,
    fontSize: 12,
    marginBottom: 6,
  },
  detailValue: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '700',
  },
  descriptionBox: {
    minHeight: 132,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 7,
    backgroundColor: '#F4F4F4',
    paddingHorizontal: 16,
    paddingTop: 11,
    marginBottom: 24,
  },
  descriptionTitle: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  descriptionText: {
    color: '#707070',
    fontSize: 12,
    lineHeight: 17,
  },
  statusContent: {
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 36,
  },
  statusCard: {
    minHeight: 646,
    borderRadius: 7,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 17,
    paddingTop: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.12,
    shadowRadius: 9,
    elevation: 4,
  },
  statusRow: {
    height: 50,
    borderBottomWidth: 1,
    borderBottomColor: '#E1E1E1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  lastStatusRow: {
    borderBottomWidth: 0,
  },
  personName: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 1,
  },
  personCode: {
    color: MUTED,
    fontSize: 10,
  },
  readBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  readDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  readText: {
    fontSize: 10,
  },
});
